### ISSUE TITLE
Server icons rotated 90°

### ISSUE THREAD

**Issue by DarkblooM-IO** [DiscordStyles/HorizontalServerList#91]
### Describe the bug
Server icons rotated 90°

### To Reproduce  
Install HSL

### Screenshots

<img width="507" height="72" alt="Image" src="https://github.com/user-attachments/assets/59add9c8-733f-4c40-964a-f704c0c9ec30" />

<img width="1081" height="73" alt="Image" src="https://github.com/user-attachments/assets/766a0f18-0dbc-46ef-b889-0fb3b01e0c93" />

### Infomation (please complete the following information)
**Discord channel**: Stable
**OS**: Linux (CachyOS)
**Mod**: Vencord (Vesktop)
**Discord language**: US English

### Additional context
\-

**Comment by fail0verfl0w** [comment]
Same issue here using Vencord and Stable discord release however running Windows 11 Pro version 24H2 (OS Build 26.100.7462) 

I think this started happening after the last Vencord update.

**Comment by fail0verfl0w** [comment]
Copy-pasting @PoTPeM 's code from the previous issue, that worked just fine for me with no theme applied and custom CSS: 


> .content__5e434 {
>   margin-top: var(--custom-guild-list-width);
>   overflow: visible !important;
> }
> :fullscreen .content__5e434 {
>   margin: 0 !important;
> }
> #app-mount .sidebar__5e434  {
>   border-radius: 0;
>   overflow: visible !important;
> }
> #app-mount .guilds__5e434 {
>   transform-origin: top left;
>   rotate: -90deg;
>   height: 100vw !important;
>   bottom: unset;
>   position: absolute !important;
>   left: 0;
> }
> #app-mount .tree_ef3116 {
>   padding-top: var(--HSL-top-padding, var(--size-sm));
> }
> #app-mount .wrapper__6e9f8,.folderPreviewWrapper__48112,.folderIcon__48112,.upperBadge_cc5dd2 {
>   rotate: 90deg;
> }
> 
> #app-mount .itemsContainer_ef3116,
> #app-mount .stack_dbd263 {
>   flex-direction: var(--HSL-server-direction);
>   justify-content: var(--HSL-server-alignment);
> }
> 
> 
> .container_c48ade > div[style]:not(.base_c48ade) {
>   width: 100vw !important;
>   height: var(--custom-guild-list-width) !important;
>   position: absolute;
>   top: calc(var(--custom-guild-list-width) + var(--custom-app-top-bar-height));
>   pointer-events: none;
>   z-index: 1;
> }
> .container_c48ade > div[style]:not(.base_c48ade) .guilds_c48ade {
>   pointer-events: all;
> }
> .container_c48ade > div[style]:not(.base_c48ade) + .base_c48ade .content__5e434 {
>   margin-top: calc(var(--custom-guild-list-width) * 2);
> }
> 
> 
> :root {
>   --HSL-server-direction: column; /* Direction of the server list. | OPTIONS: column, column-reverse | DEFAULT: column */
>   --HSL-server-alignment: flex-start; /* Alignment of the server list. | OPTIONS: flex-start, center, flex-end | DEFAULT: flex-start */
> }
> 
> [class*=avatardecoration i]{
>     display: none;
> }

**Comment by F0RMATTED** [comment]
> > <img alt="Image" width="848" height="377" src="https://private-user-images.githubusercontent.com/94066755/525702932-630affe4-7012-48fc-ab3a-aa35f4f62008.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjU1MTM4ODMsIm5iZiI6MTc2NTUxMzU4MywicGF0aCI6Ii85NDA2Njc1NS81MjU3MDI5MzItNjMwYWZmZTQtNzAxMi00OGZjLWFiM2EtYWEzNWY0ZjYyMDA4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMjEyVDA0MjYyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI1MDM3NTE0YTRhN2VhMmIyNjYyZmZiYTlkNWJlZDJkOTAzNWNlNDBlNzkzZmQyMzA1NzFjM2M1MjY3NTYxMGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0._U4C_rWys0P1mz3N8yXO7q8jU8zN5EKKOJ7BRViO-S4"> Looks like this guy came up with the solution.
> 
> Thanks for the screenshot and not just copy and pasting it... Edit: I did us all a favor
> 
> #app-mount .wrapper__6e9f8,.folderPreviewWrapper__48112,.folderIcon__48112,.upperBadge_cc5dd2 {
>     rotate: -90deg;
> }
> 
> -90 because 90 was updside down

So this works, but the Discord icon itself on the very left also rotates with this same line of code.

**Comment by Knightsundere** [comment]
> I find this snippet to work best
> 
> /* HSL server icons fix */
> [aria-label="Servers"] .wrapper__6e9f8 {
>   rotate: -90deg;
> }

works perfect, thank you

**Comment by HirschBerge** [comment]
> Can someone please upload the entire code that works for them? I had it working and now they are located on the left side again and I've not touched anything and BD hasn't had another update as far as I know. Or has Discord updated the structure of the class names again?

```
/**
 * @name Horizontal Server List
 * @author Gibbu
 * @version 3.0.0
 * @description Moves the server list from the left to the top of Discord.
 * @source https://github.com/DiscordStyles/HorizontalServerList
 * @invite ZHthyCw
*/

@import url('https://discordstyles.github.io/HorizontalServerList/HorizontalServerList.css');



/* Bottom HorizontalServerList. Simply remove the comments surrounding the @import to enable it. */
/* @import url("https://discordstyles.github.io/HorizontalServerList/bottomhsl.css"); */
.wrapper__6e9f8:not([data-list-item-id="guildsnav___home"]) {
  rotate: -90deg;
}
```
It's just three lines to add. It can't be that hard to read?

**Comment by Vehdrehl** [comment]
> Can someone please upload the entire code that works for them? I had it working and now they are located on the left side again and I've not touched anything and BD hasn't had another update as far as I know. Or has Discord updated the structure of the class names again?

Same issue here. Reverted to not working whatsoever with no update.

**Comment by Vehdrehl** [comment]
Icons in the top left indicating users in voice chat, sharing screen etc are still incorrectly rotated. 

User in voice chat: https://i.imgur.com/c83hZPd.png
User sharing screen: https://i.imgur.com/J2O2p2K.png
Upcoming events: https://i.imgur.com/L4FCWty.png

**Comment by HirschBerge** [comment]
Today's update broke entirely, and no everything is on the left side again

**Comment by Vehdrehl** [comment]
> Today's update broke entirely, now the server list is entirely just gone. Just blank space

I think someone needs to open a new issue as this was marked as complete and closed for some reason.

**Comment by OniHelix** [comment]
It was fixed for 5 seconds, then broke again. Discord is getting really annoying right now.

**Comment by HirschBerge** [comment]
@Gibbu @DarkblooM-IO 
Could one of you reopen this since it's not fixed?

**Comment by Gibbu** [comment]
Works for me :tm:

<img width="1046" height="165" alt="Image" src="https://github.com/user-attachments/assets/eab61142-8c62-414b-8626-d7ece46f92b3" />

**Comment by OniHelix** [comment]
I'll be home from work in 45 minutes. I'll check if anything's broken on my end.

**Comment by OniHelix** [comment]
Any news on compatibility with the ServerFolders plugin?

**Comment by Vehdrehl** [comment]
> Works for me ™️
> 
> <img alt="Image" width="1046" height="165" src="https://private-user-images.githubusercontent.com/20338746/528912274-eab61142-8c62-414b-8626-d7ece46f92b3.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjYyNzk0OTAsIm5iZiI6MTc2NjI3OTE5MCwicGF0aCI6Ii8yMDMzODc0Ni81Mjg5MTIyNzQtZWFiNjExNDItOGM2Mi00MTRiLTg2MjYtZDdlY2U0NmY5MmIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMjIxVDAxMDYzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMzNjBhNGM0ODkwZmVkMjA4M2FhNmY0OWI5MTI0ZjNjNjAxNTk3ZDA4MzNlNTFiNWJhMjU4NWJiNGNhZmZmZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.lufSZ9GdLHIQkqzdzKVtNIyzpOXtJo_V42L0NiNxjbo">

And the badge notifications too? For users in VC etc?

**Comment by DarkblooM-IO** [comment]
> @Gibbu @DarkblooM-IO 
> Could one of you reopen this since it's not fixed?

It's fixed for me
